---

- name: "installing docker_compose: install dependency"
  package:
    state: latest
    name:
      - python3-pip
      - python3-setuptools
      - python-setuptools
  register: dep_check

- name: "installing docker_compose: install docker_compose"
  pip:
    executable: pip3
    state: latest
    name:
      - docker-compose
  when:
  - (dep_check is succeeded)


